chore: add retry to addIPfs and getIpfsMetadata
Scaffold-Stark/speedrunstark pull request #151
Opened 2024-10-04 12:41 UTC by ShantelPeters

Fixes #141 
## Types of change

- [ ] Feature
- [ ] Bug
- [x] Enhancement

## Comments (optional)
By adding retry mechanisms to both the addToIPFS and getMetadataFromIPFS functions, I’ve addressed the NFT duplication issue during fast minting on Sepolia. The retries ensure multiple attempts to handle delays or interruptions, reducing the chances of Token ID 1 being duplicated due to incomplete metadata processing

2024-10-04 16:49 UTC, metalboyrick commented
Hi @ShantelPeters, is this PR ready to review, feel free to request reviews if you feel ready!

2024-10-04 22:18 UTC, Nadai2010 commented
Hi @ShantelPeters the metadata of the TokenID 1 the NFT is still being duplicate in Sepolia.

Flow:
- Deploy the NFT in Sepolia, 
- Mint and quickly as soon as the mint button appears again, repeat the process and you will be able to see this error

![imagen](https://github.com/user-attachments/assets/603de2be-59a7-42ca-b003-30e6f1bb9ff5)

[NFT in Explorer](https://sepolia.starkscan.co/nft-contract/0x00ae55207bddf9f6d14048efd68fc14e8f90b7a78d772785915ac26186d2962b#items)

2024-10-05 04:30 UTC, metalboyrick requested changes
Hi @ShantelPeters, thanks for the PR!

Left minor comments

2024-10-05 04:30 UTC, metalboyrick commented on packages/nextjs/app/ipfsDownload/page.tsx
> +    const maxAttempts = 2;
Would prefer to extract this in a separate `constants` file with `SCREAMING_SNAKE_CASE_NOTATION`

2024-10-05 04:30 UTC, metalboyrick commented on packages/nextjs/app/ipfsDownload/page.tsx
> +    const maxAttempts = 2;
Same case as the upload page too

2024-10-05 09:29 UTC, ShantelPeters commented
@metalboyrick Kindly review

2024-10-05 15:27 UTC, metalboyrick approved these changes
Neat! Looks good to me, kindly wait for @Nadai2010 and @gianalarcon comments should they have any more, thanks for the hard work!

2024-10-05 17:43 UTC, Nadai2010 approved these changes
Good job, now getIpfsMetadata works perfectly

![imagen](https://github.com/user-attachments/assets/ff98a1af-011f-41cc-be01-687107aa7652)

2024-10-05 17:43 UTC, merged