fix build error in vercel deploy
Scaffold-Stark/speedrunstark pull request #160
Opened 2024-10-24 13:16 UTC by huisq

Issue Overview
as titled, error: yarn next build failed

Solution
resolved by modifying ./packages/nextjs/utils/scaffold-stark/contractsData.ts
add "decodeBigIntArrayToText"

2024-10-25 05:14 UTC, 0xquantum3labs requested changes

2024-10-25 05:14 UTC, 0xquantum3labs commented on packages/nextjs/utils/scaffold-stark/contractsData.ts
> +export function decodeBigIntArrayToText(byteArray: string[]) {
i think we can just remove the `import decode ...` from the `MyHoldings.tsx` file.

2024-10-25 05:14 UTC, 0xquantum3labs commented on packages/nextjs/utils/scaffold-stark/contractsData.ts
> +export function decodeBigIntArrayToText(byteArray: string[]) {
we dont need to define this function.

2024-10-26 08:06 UTC, 0xquantum3labs commented on packages/nextjs/utils/scaffold-stark/contractsData.ts
> +export function decodeBigIntArrayToText(byteArray: string[]) {
@huisq can you update this PR please ? thanks 🙌

2024-10-27 04:08 UTC, huisq commented
fixed PR

2024-10-27 04:15 UTC, jrcarlos2000 approved these changes

2024-10-27 04:15 UTC, merged

2024-10-27 04:16 UTC, jrcarlos2000 commented
> fixed PR

Thanks 🙌🏽