feat: Synced New changes from Scaffold Stark to SpeedRun Base Template
Scaffold-Stark/speedrunstark pull request #174
Opened 2024-12-14 18:53 UTC by michojekunle

# Synced New changes from Scaffold Stark to SpeedRun Base Template 

Fixes #171 

## Types of change

- [ ] Feature
- [ ] Bug
- [ ] Enhancement

2024-12-14 18:55 UTC, michojekunle commented
Hi @metalboyrick @Nadai2010, this is a pull request regarding the issue I was assigned. 

Please review

2024-12-14 20:29 UTC, Nadai2010 requested changes

2024-12-14 20:29 UTC, Nadai2010 commented on packages/nextjs/app/debug/_components/contract/TxReceipt.tsx
Does not match, use CopyToCliboard and the file as is in main.

https://github.com/Scaffold-Stark/scaffold-stark-2/blob/main/packages/nextjs/app/debug/_components/contract/TxReceipt.tsx

2024-12-14 20:29 UTC, Nadai2010 commented on packages/nextjs/app/page.tsx
Restore this file, in the base Template only the Example View should appear.

2024-12-14 20:29 UTC, Nadai2010 commented on packages/nextjs/components/scaffold-stark/Address.tsx
> +const TypedCopyToClipboard = CopyToClipboard as unknown as React.FC<{
Here I added the TypedCopyClipboard again, remove it, and check that the rest is correct in the file

https://github.com/Scaffold-Stark/scaffold-stark-2/blob/main/packages/nextjs/components/scaffold-stark/Address.tsx

2024-12-14 20:29 UTC, Nadai2010 commented on packages/nextjs/components/scaffold-stark/ClassHash.tsx
> +const TypedCopyToClipboard = CopyToClipboard as unknown as React.FC<{
Here I added the TypedCopyClipboard again, removed.

2024-12-14 20:29 UTC, Nadai2010 commented on packages/nextjs/components/scaffold-stark/CustomConnectButton/AddressInfoDropdown.tsx
> +const TypedCopyToClipboard = CopyToClipboard as unknown as React.FC<{
Here I added the TypedCopyClipboard again, removed.

2024-12-14 20:29 UTC, Nadai2010 commented on packages/nextjs/app/debug/_components/contract/__test__/utilsContract.test.tsx
No Add test, remove utilsContract.test.tsx and utilsDisplay.test.tsx

2024-12-14 20:29 UTC, Nadai2010 commented on packages/nextjs/app/debug/_components/contract/__test__/utilsDisplay.test.tsx
No Add test, remove utilsContract.test.tsx and utilsDisplay.test.tsx

2024-12-14 20:29 UTC, Nadai2010 commented on packages/nextjs/hooks/scaffold-stark/__tests__/useDeployedContractInfo.test.ts
Hooks Tests should not be part of Speedrun, please mix old and new ones.

Check the ch-0, ch-1, ch-2 and ch-3

2024-12-14 20:29 UTC, Nadai2010 commented on packages/nextjs/hooks/scaffold-stark/__tests__/useScaffoldContract.test.ts
Hooks Tests should not be part of Speedrun, please mix old and new ones.

Check the ch-0, ch-1, ch-2 and ch-3

2024-12-14 20:29 UTC, Nadai2010 commented on packages/nextjs/public/debug-image.png
Remove this file

2024-12-14 20:29 UTC, Nadai2010 commented on packages/nextjs/public/rpc-version.png
Remove this file

2024-12-14 20:29 UTC, Nadai2010 commented on packages/nextjs/public/scaffold-config.png
Remove this file

2024-12-14 21:25 UTC, michojekunle commented
Alright Thank you so much for the Review @Nadai2010, 

I've implemented the required changes Please review

2024-12-15 10:30 UTC, Nadai2010 approved these changes
For me everything is fine, good job

2024-12-16 06:52 UTC, metalboyrick commented
@Nadai2010 for this PR do we want to wait for more changes from scaffold stark? if not i think you can merge it, looks good on my end

2024-12-16 07:46 UTC, Nadai2010 commented
We can merged, we can't wait for the new changes, at the end of the hack I will do the sync again. Thanks @michojekunle  and @metalboyrick

2024-12-16 07:46 UTC, merged