feat: refactor chaper 0 + integrate features of OZ 0.20.0
Scaffold-Stark/speedrunstark pull request #175
Opened 2024-12-15 22:53 UTC by manlikeHB

# Task name here

Fixes #172 

## Types of change

- [ ] Enhancement

## Comments (optional)

2024-12-16 06:49 UTC, metalboyrick requested changes
cc @Nadai2010

2024-12-16 06:49 UTC, metalboyrick commented on .tool-versions
> +scarb 2.9.1
please bump to `2.9.2`

2024-12-16 07:57 UTC, Nadai2010 commented
The main idea here is to make the "[`YourCollectible`](https://github.com/Scaffold-Stark/speedrunstark/blob/challenge-0-simple-nft/packages/snfoundry/contracts/src/YourCollectible.cairo)" NFT better with the best possible integrations of the [latest versions the OZ](https://github.com/OpenZeppelin/cairo-contracts/releases), you can check [the news ERC721 the OZ](https://github.com/Scaffold-Stark/speedrunstark/blob/challenge-0-simple-nft/packages/snfoundry/contracts/src/test/TestContract.cairo).

- Check that the deployment in devnet 0.2.3 and sepolia works well with ch-0 in UI.
- Pass all tests of snfoundry 0.34.0 and adapt the [TestContract.cairo](https://github.com/Scaffold-Stark/speedrunstark/blob/challenge-0-simple-nft/packages/snfoundry/contracts/src/test/TestContract.cairo) for the new contract.

2024-12-16 07:58 UTC, Nadai2010 requested changes

2024-12-16 07:58 UTC, Nadai2010 commented on .tool-versions
>  starknet-foundry 0.33.0
starknet-foundry 0.34.0
starknet-devnet 0.2.3

2024-12-16 07:58 UTC, Nadai2010 commented on packages/snfoundry/contracts/Scarb.toml
>  snforge_std = "0.33.0"
0.34.0

2024-12-16 07:58 UTC, Nadai2010 commented on packages/snfoundry/contracts/Scarb.toml
> +starknet = "2.9.1"
2.9.2

2024-12-17 11:02 UTC, manlikeHB commented
After implementing the requested changes, everything still works as expect both on devnet and sepolia testnet. all tests pass locally as well.

If there is any particular changes you'd like to see let me know please.

2024-12-17 11:13 UTC, Nadai2010 commented
Hi, thanks for the contribution, although I don't see any changes in YourCollectible.cairo, do you think you can refactor or are there important improvements in the latest versions to integrate into this contract?

It should also be synchronized with the latest version of base-template [this last PR](https://github.com/Scaffold-Stark/speedrunstark/pull/174)

2024-12-17 11:55 UTC, manlikeHB commented
There are no improvements to be added, most of the changes don't affect the current contract/implementation. but for synchronization with the base-template, I'll work on that.

2024-12-17 11:57 UTC, Nadai2010 reviewed
Perfect, thanks for your contributions.

2024-12-19 23:35 UTC, manlikeHB commented
Sorry this took a while, faced some issues while syncing causing the code to break at different points but its all good and fixed now.

2024-12-20 07:33 UTC, Nadai2010 requested changes
Good job @manlikeHB , thank you very much, looking forward to the small change for the merged one

2024-12-20 07:33 UTC, Nadai2010 commented on packages/nextjs/contracts/deployedContracts.ts
This file no commit please

2024-12-20 12:50 UTC, merged